# Generated by Django 4.2.8 on 2023-12-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('System_Outage', 'System_Outage'), ('Performance_Issue', 'Performance_Issue'), ('Data_Inconsistency', 'Data_Inconsistency'), ('Network_Issue', 'Network_Issue'), ('Application_Crash', 'Application_Crash'), ('Security_Breach', 'Security_Breach')], max_length=128)),
                ('severity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In_Progress', 'In_Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=128)),
                ('assigned_to', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('assigned_incident', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='incident_alerting.incident')),
            ],
        ),
    ]
